### ISSUE TITLE
Localisation error when using color field type

### ISSUE THREAD

**Issue by andreydruz** [TypeRocket/typerocket-framework#1]
Hello,

TypeRocket: v5.0.47
PHP: 7.4.21 
WordPress: 5.8.1

If I trying to add color field type to repeater I get the error.

Demo:
https://drive.google.com/uc?id=1nCTQ0Pa_Jtjx5clqdCANuKrpmI_1A70J

Code with gives an error in plugin :
```
        $box = tr_meta_box('Top 10 Links')->apply($postType);
        $box->addScreen('event');
        $box->setCallback(function() {
            $form = tr_form();
            $repeater = $form->repeater('Top 10 Link')->setFields([
                $form->text('Name'),
                $form->text('Bonus'),
                $form->image('Logo'),
                $form->text('Text on logo'),
                $form->color('Text on logo color'),
                $form->range('Stars')->setMax(5)->setMin(0)->setStep(0.5),
                $form->range('Rating')->setMax(10)->setMin(0)->setStep(0.1),
                $form->url('Redirect URL'),
                $form->url('Review URL'),
                $form->textarea('Note')
            ]);
            echo $repeater;
        });
```

Error:
`Whoops \ Exception \ ErrorException (E_USER_NOTICE)
WP_Scripts::localize was called <strong>incorrectly</strong>. The <code>$l10n</code> parameter must be an array. To pass arbitrary data to scripts, use the <code>wp_add_inline_script()</code> function instead. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.7.0.)`

**Comment by kevindees** [comment]
Hey @andreydruz 

This bug is patched and will be released in the next plugin update.

https://github.com/TypeRocket/core/releases/tag/v5.0.100

Thanks,
Kevin
